### ISSUE TITLE
ERROR:wally.report:Diring hdd report generation

### ISSUE THREAD

**Issue by psycle91** [Mirantis/disk_perf_test_tool#16]
Hi,

after i started an hdd test on a local attatched disk, under debian 9. 
I get following error durring report creation:

10:54:24 - INFO     - wally           - Start html_report_stage
INFO:wally:Start html_report_stage
10:54:24 - ERROR    - wally.report    - Diring hdd report generation
Traceback (most recent call last):
  File "wally/report.py", line 821, in make_io_report
    report = func(dinfo, lab_info, comment)
  File "wally/report.py", line 642, in make_hdd_report
    images = make_plots(perf_infos, plots)
  File "wally/report.py", line 511, in make_plots
    error2=data_dev)
  File "wally/report.py", line 374, in io_chart
    matplotlib.rcParams.update({'font.size': 10})
NameError: global name 'matplotlib' is not defined
ERROR:wally.report:Diring hdd report generation
Traceback (most recent call last):
  File "wally/report.py", line 821, in make_io_report
    report = func(dinfo, lab_info, comment)
  File "wally/report.py", line 642, in make_hdd_report
    images = make_plots(perf_infos, plots)
  File "wally/report.py", line 511, in make_plots
    error2=data_dev)
  File "wally/report.py", line 374, in io_chart
    matplotlib.rcParams.update({'font.size': 10})
NameError: global name 'matplotlib' is not defined

Would be great if i can get a fix for that. 

OS: Debian 9.4
To get fio running i have copied the fio binaries and renamed it to fio_stretch_x86_64.bz2
I have installed disk_perf_test_tool via:
git clone https://github.com/Mirantis/disk_perf_test_tool.git
I have executed: /disk_perf_test_tool/scripts/install.sh

After that i have run local HDD Test via:
python -m wally test hdd configs-examples/hdd2.yaml

hdd2.yaml:
include: default.yaml

explicit_nodes:
    local: testnode

tests:
    - io:
        cfg: hdd
        params:
            FILENAME: /dev/vdb
            TEST_FILE_SIZE: 2G

**Comment by koder-ua** [comment]
Sry, v1 is not supported anymore. Issue does not appear in v2. Will close this
